server:
  port: 9079
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fish_backfonted
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
      database: 10

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  # 日志文件路径（确保目录存在且有权限）
  file:
    name: /var/log/backend/yychat.log
  # 日志级别（INFO/DEBUG/ERROR，级别太低会导致日志少）
  level:
    root: INFO
    com.example.anonymouschat: DEBUG  # 业务包日志级别
  # 日志文件滚动配置（可选，避免文件过大）
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7

file:
  user-name: /root/test.json
  sensitive-file:


